<?php
			$optionsArray = array( 'totals' => array( 'idusrglobal' => array( 'totalsType' => '' ),
'id_fk' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_nombresfull' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_dep_sup' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'global_rol_contratos' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'idusrglobal',
'id_fk',
'Username',
'usr_email',
'usr_nombresfull',
'usr_personalid',
'global_rol_contratos',
'usr_dep',
'usr_cargo',
'usr_dep_sup',
'usr_name',
'usr_lname' ),
'exportFields' => array( 'idusrglobal',
'id_fk',
'Username',
'usr_email',
'usr_nombresfull',
'usr_personalid',
'global_rol_contratos',
'usr_dep',
'usr_cargo',
'usr_dep_sup',
'usr_name',
'usr_lname' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'idusrglobal' => array( 'export_field' ),
'id_fk' => array( 'export_field1' ),
'Username' => array( 'export_field2' ),
'usr_email' => array( 'export_field4' ),
'usr_nombresfull' => array( 'export_field7' ),
'usr_personalid' => array( 'export_field8' ),
'global_rol_contratos' => array( 'export_field30' ),
'usr_dep' => array( 'export_field65' ),
'usr_cargo' => array( 'export_field66' ),
'usr_dep_sup' => array( 'export_field3' ),
'usr_name' => array( 'export_field5' ),
'usr_lname' => array( 'export_field6' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field7',
'export_field8',
'export_field30',
'export_field65',
'export_field66',
'export_field3',
'export_field5',
'export_field6' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field30' => 'grid',
'export_field65' => 'grid',
'export_field66' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field7',
'export_field8',
'export_field30',
'export_field65',
'export_field66',
'export_field3',
'export_field5',
'export_field6' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field7',
'export_field8',
'export_field30',
'export_field65',
'export_field66',
'export_field3',
'export_field5',
'export_field6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'idusrglobal',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'id_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Username',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'usr_email',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'usr_nombresfull',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'usr_personalid',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'global_rol_contratos',
'type' => 'export_field' ),
'export_field65' => array( 'field' => 'usr_dep',
'type' => 'export_field' ),
'export_field66' => array( 'field' => 'usr_cargo',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'usr_dep_sup',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'usr_name',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'usr_lname',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>