<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_consecutivo',
'cxc_cont',
'cxc_razonsocial',
'cxc_periodoi',
'cxc_periodof',
'cxc_valor',
'cxc_planilla',
'cxc_planillafecha',
'cxc_planillavalor',
'sup_name',
'sup_cargo',
'sup_dep',
'cxc_planilla_arl',
'cxc_planilla_arl_fecha',
'cxc_planilla_arl_periodo',
'cxc_planilla_arl_valor',
'cxc_planilla_obs',
'cxc_planilla_pension',
'cxc_planilla_pension_fecha',
'cxc_planilla_pension_periodo',
'cxc_planilla_pension_valor',
'cxc_planillaperiodo',
'inf_mes',
'inf_tipopago' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_consecutivo' => array( 'import_field6' ),
'cxc_cont' => array( 'import_field8' ),
'cxc_razonsocial' => array( 'import_field10' ),
'cxc_periodoi' => array( 'import_field13' ),
'cxc_periodof' => array( 'import_field14' ),
'cxc_valor' => array( 'import_field15' ),
'cxc_planilla' => array( 'import_field17' ),
'cxc_planillafecha' => array( 'import_field18' ),
'cxc_planillavalor' => array( 'import_field19' ),
'sup_name' => array( 'import_field20' ),
'sup_cargo' => array( 'import_field21' ),
'sup_dep' => array( 'import_field22' ),
'cxc_planilla_arl' => array( 'import_field' ),
'cxc_planilla_arl_fecha' => array( 'import_field1' ),
'cxc_planilla_arl_periodo' => array( 'import_field2' ),
'cxc_planilla_arl_valor' => array( 'import_field3' ),
'cxc_planilla_obs' => array( 'import_field4' ),
'cxc_planilla_pension' => array( 'import_field5' ),
'cxc_planilla_pension_fecha' => array( 'import_field7' ),
'cxc_planilla_pension_periodo' => array( 'import_field9' ),
'cxc_planilla_pension_valor' => array( 'import_field11' ),
'cxc_planillaperiodo' => array( 'import_field12' ),
'inf_mes' => array( 'import_field16' ),
'inf_tipopago' => array( 'import_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field6',
'import_field8',
'import_field10',
'import_field13',
'import_field14',
'import_field15',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field7',
'import_field9',
'import_field11',
'import_field12',
'import_field16',
'import_field23' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field6' => 'grid',
'import_field8' => 'grid',
'import_field10' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field7' => 'grid',
'import_field9' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field16' => 'grid',
'import_field23' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field6',
'import_field8',
'import_field10',
'import_field13',
'import_field14',
'import_field15',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field7',
'import_field9',
'import_field11',
'import_field12',
'import_field16',
'import_field23' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field6',
'import_field8',
'import_field10',
'import_field13',
'import_field14',
'import_field15',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field7',
'import_field9',
'import_field11',
'import_field12',
'import_field16',
'import_field23' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field6' => array( 'field' => 'id_consecutivo',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cxc_cont',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cxc_razonsocial',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'cxc_periodoi',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cxc_periodof',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'cxc_valor',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'cxc_planilla',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'cxc_planillafecha',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'cxc_planillavalor',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'sup_name',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'sup_cargo',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'sup_dep',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'cxc_planilla_arl',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cxc_planilla_arl_fecha',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cxc_planilla_arl_periodo',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cxc_planilla_arl_valor',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cxc_planilla_obs',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cxc_planilla_pension',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cxc_planilla_pension_fecha',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cxc_planilla_pension_periodo',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cxc_planilla_pension_valor',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'cxc_planillaperiodo',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'inf_mes',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'inf_tipopago',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>