<?php
			$optionsArray = array( 'details' => array( 'informe_intersup_anexos_supervisor' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'informe_intersup_oe_supervisor' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'q_bandejaentrada_supervisores1' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'inf_consecutivo',
'inf_avgejecucion',
'inf_estado',
'inf_numerocontrato',
'inf_doccontratista',
'inf_nombrecontratista',
'inf_fechapresenta',
'id_cont_fk',
'inf_hash',
'inf_mail_a',
'inf_mail_b',
'inf_declarainconf',
'inf_declarainconf_obs',
'inf_incumplimiento',
'inf_incumplimiento_obs',
'cont_cesion',
'cont_modifica',
'inf_intersup',
'inf_nombre',
'inf_cargo',
'inf_dependencia',
'inf_supervisoremail',
'supa_documento_id',
'supa_cargo_id',
'supa_dependencia_id',
'supa_email',
'supa_nombres',
'supa_apellidos',
'supb_documento_id',
'supb_cargo_id',
'supb_dependencia_id',
'supb_email',
'supb_nombres',
'supb_apellidos',
'inf_periodicidad',
'inf_valorcontrato',
'inf_fechasuscripcion',
'inf_objeto',
'inf_fechacont_i',
'inf_fechacont_f',
'inf_cdp',
'inf_rp',
'inf_rubrocode',
'inf_rubroname',
'inf_plazo',
'inf_vigencia',
'url_secop',
'inf_usopresupuestal',
'mun_ejec',
'inf_anio',
'inf_prenum',
'cert_modalidad' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_consecutivo' => array( 'integrated_edit_field1' ),
'inf_avgejecucion' => array( 'integrated_edit_field29' ),
'inf_estado' => array( 'integrated_edit_field3' ),
'inf_numerocontrato' => array( 'integrated_edit_field8' ),
'inf_doccontratista' => array( 'integrated_edit_field9' ),
'inf_nombrecontratista' => array( 'integrated_edit_field10' ),
'inf_fechapresenta' => array( 'integrated_edit_field4' ),
'id_cont_fk' => array( 'integrated_edit_field' ),
'inf_hash' => array( 'integrated_edit_field2' ),
'inf_mail_a' => array( 'integrated_edit_field53' ),
'inf_mail_b' => array( 'integrated_edit_field54' ),
'inf_declarainconf' => array( 'integrated_edit_field31' ),
'inf_declarainconf_obs' => array( 'integrated_edit_field32' ),
'inf_incumplimiento' => array( 'integrated_edit_field33' ),
'inf_incumplimiento_obs' => array( 'integrated_edit_field34' ),
'cont_cesion' => array( 'integrated_edit_field12' ),
'cont_modifica' => array( 'integrated_edit_field23' ),
'inf_intersup' => array( 'integrated_edit_field24' ),
'inf_nombre' => array( 'integrated_edit_field25' ),
'inf_cargo' => array( 'integrated_edit_field26' ),
'inf_dependencia' => array( 'integrated_edit_field27' ),
'inf_supervisoremail' => array( 'integrated_edit_field48' ),
'supa_documento_id' => array( 'integrated_edit_field7' ),
'supa_cargo_id' => array( 'integrated_edit_field38' ),
'supa_dependencia_id' => array( 'integrated_edit_field39' ),
'supa_email' => array( 'integrated_edit_field40' ),
'supa_nombres' => array( 'integrated_edit_field30' ),
'supa_apellidos' => array( 'integrated_edit_field37' ),
'supb_documento_id' => array( 'integrated_edit_field42' ),
'supb_cargo_id' => array( 'integrated_edit_field45' ),
'supb_dependencia_id' => array( 'integrated_edit_field46' ),
'supb_email' => array( 'integrated_edit_field47' ),
'supb_nombres' => array( 'integrated_edit_field43' ),
'supb_apellidos' => array( 'integrated_edit_field44' ),
'inf_periodicidad' => array( 'integrated_edit_field5' ),
'inf_valorcontrato' => array( 'integrated_edit_field11' ),
'inf_fechasuscripcion' => array( 'integrated_edit_field18' ),
'inf_objeto' => array( 'integrated_edit_field17' ),
'inf_fechacont_i' => array( 'integrated_edit_field19' ),
'inf_fechacont_f' => array( 'integrated_edit_field20' ),
'inf_cdp' => array( 'integrated_edit_field13' ),
'inf_rp' => array( 'integrated_edit_field14' ),
'inf_rubrocode' => array( 'integrated_edit_field15' ),
'inf_rubroname' => array( 'integrated_edit_field16' ),
'inf_plazo' => array( 'integrated_edit_field21' ),
'inf_vigencia' => array( 'integrated_edit_field22' ),
'url_secop' => array( 'integrated_edit_field55' ),
'inf_usopresupuestal' => array( 'integrated_edit_field28' ),
'mun_ejec' => array( 'integrated_edit_field35' ),
'inf_anio' => array( 'integrated_edit_field51' ),
'inf_prenum' => array( 'integrated_edit_field52' ),
'cert_modalidad' => array( 'integrated_edit_field36' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field29',
'integrated_edit_field3',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field53',
'integrated_edit_field54' ),
'section3' => array( 'section',
'section1',
'integrated_edit_field12',
'integrated_edit_field23' ),
'section4' => array( 'integrated_edit_field31',
'integrated_edit_field32' ),
'section5' => array( 'integrated_edit_field33',
'integrated_edit_field34' ),
'section2' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field48' ),
'section6' => array( 'integrated_edit_field7',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field30',
'integrated_edit_field37' ),
'section7' => array( 'integrated_edit_field42',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field43',
'integrated_edit_field44' ),
'section1' => array( 'integrated_edit_field5',
'integrated_edit_field11',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field55',
'integrated_edit_field28',
'integrated_edit_field35',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field36' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field29' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field53' => 'section',
'integrated_edit_field54' => 'section',
'section' => 'section3',
'section1' => 'section3',
'integrated_edit_field12' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field31' => 'section4',
'integrated_edit_field32' => 'section4',
'integrated_edit_field33' => 'section5',
'integrated_edit_field34' => 'section5',
'integrated_edit_field24' => 'section2',
'integrated_edit_field25' => 'section2',
'integrated_edit_field26' => 'section2',
'integrated_edit_field27' => 'section2',
'integrated_edit_field48' => 'section2',
'integrated_edit_field7' => 'section6',
'integrated_edit_field38' => 'section6',
'integrated_edit_field39' => 'section6',
'integrated_edit_field40' => 'section6',
'integrated_edit_field30' => 'section6',
'integrated_edit_field37' => 'section6',
'integrated_edit_field42' => 'section7',
'integrated_edit_field45' => 'section7',
'integrated_edit_field46' => 'section7',
'integrated_edit_field47' => 'section7',
'integrated_edit_field43' => 'section7',
'integrated_edit_field44' => 'section7',
'integrated_edit_field5' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field18' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field19' => 'section1',
'integrated_edit_field20' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field15' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field21' => 'section1',
'integrated_edit_field22' => 'section1',
'integrated_edit_field55' => 'section1',
'integrated_edit_field28' => 'section1',
'integrated_edit_field35' => 'section1',
'integrated_edit_field51' => 'section1',
'integrated_edit_field52' => 'section1',
'integrated_edit_field36' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c16' ),
'integrated_edit_field53' => array( 'location' => 'section',
'cellId' => 'c17' ),
'integrated_edit_field54' => array( 'location' => 'section',
'cellId' => 'c18' ),
'section' => array( 'location' => 'section3',
'cellId' => 'c' ),
'section1' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field12' => array( 'location' => 'section3',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field31' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'integrated_edit_field33' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section5',
'cellId' => 'c2' ),
'integrated_edit_field24' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field27' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field48' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field7' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section6',
'cellId' => 'c2' ),
'integrated_edit_field39' => array( 'location' => 'section6',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'section6',
'cellId' => 'c4' ),
'integrated_edit_field30' => array( 'location' => 'section6',
'cellId' => 'c6' ),
'integrated_edit_field37' => array( 'location' => 'section6',
'cellId' => 'c7' ),
'integrated_edit_field42' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field45' => array( 'location' => 'section7',
'cellId' => 'c2' ),
'integrated_edit_field46' => array( 'location' => 'section7',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'section7',
'cellId' => 'c4' ),
'integrated_edit_field43' => array( 'location' => 'section7',
'cellId' => 'c6' ),
'integrated_edit_field44' => array( 'location' => 'section7',
'cellId' => 'c7' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field19' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field20' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field15' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c11' ),
'integrated_edit_field21' => array( 'location' => 'section1',
'cellId' => 'c12' ),
'integrated_edit_field22' => array( 'location' => 'section1',
'cellId' => 'c13' ),
'integrated_edit_field55' => array( 'location' => 'section1',
'cellId' => 'c14' ),
'integrated_edit_field28' => array( 'location' => 'section1',
'cellId' => 'c15' ),
'integrated_edit_field35' => array( 'location' => 'section1',
'cellId' => 'c16' ),
'integrated_edit_field51' => array( 'location' => 'section1',
'cellId' => 'c17' ),
'integrated_edit_field52' => array( 'location' => 'section1',
'cellId' => 'c18' ),
'integrated_edit_field36' => array( 'location' => 'section1',
'cellId' => 'c19' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'tabs' => array( 'tabs' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field29',
'integrated_edit_field3',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field12',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field48',
'integrated_edit_field7',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field30',
'integrated_edit_field37',
'integrated_edit_field42',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field5',
'integrated_edit_field11',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field55',
'integrated_edit_field28',
'integrated_edit_field35',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field36' ),
'section' => array( 'section',
'section1' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c15' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field53' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 7 ),
'section3' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field47' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c16' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field52' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'tabs' ),
'useFullWidth' => true ),
'c6' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'useFullWidth' => true ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c12' => array( 'model' => 'c1',
'items' => array(  ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field53' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field54' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'section' ),
'useFullWidth' => true ),
'c2' => array( 'model' => 'c1',
'items' => array( 'section1' ),
'useFullWidth' => true ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field48' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field45' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field46' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field47' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field44' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ) ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field51' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field52' ) ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'informe_intersup',
'type' => 7 ) ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'buttonStyle' => 'warning',
'buttonSize' => 'normal',
'label' => array( 'type' => 0,
'text' => 'Crear informe y notificar al contratista' ),
'icon' => array( 'fa' => 'send-o' ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel',
'buttonStyle' => 'primary',
'buttonSize' => 'normal',
'icon' => array( 'fa' => 'power-off' ) ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'CONTRATISTA',
'type' => 0 ),
array( 'text' => 'ACTIVIDADES',
'type' => 0 ),
array( 'text' => 'SUPERVISOR 1 | APOYO',
'type' => 0 ),
array( 'text' => 'SUPERVISOR 2',
'type' => 0 ),
array( 'text' => 'SUPERVISOR 3',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section3',
'section2',
'section6',
'section7',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field1' => array( 'field' => 'inf_consecutivo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'inf_avgejecucion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'inf_estado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'inf_numerocontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'inf_doccontratista',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'inf_nombrecontratista',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'inf_fechapresenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'id_cont_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_cont_fk',
'table' => 'informe_intersup',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'inf_hash',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'inf_hash',
'table' => 'informe_intersup',
'type' => 3 ),
'font-family' => 'Roboto',
'bold' => true ),
'integrated_edit_field53' => array( 'field' => 'inf_mail_a',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field54' => array( 'field' => 'inf_mail_b',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => '¿Declara inconformidad en el cumplimiento del contrato para este periodo reportado?',
'type' => 0 ),
'location' => 'section4',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field31' => array( 'field' => 'inf_declarainconf',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'inf_declarainconf_obs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'inf_declarainconf_obs',
'table' => 'informe_intersup',
'type' => 3 ),
'placeholder' => array( 'field' => 'inf_declarainconf_obs',
'table' => null,
'type' => 5 ) ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => '¿Declara incumplimiento en el desarrollo del contrato para este periodo reportado?',
'type' => 0 ),
'location' => 'section5',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field33' => array( 'field' => 'inf_incumplimiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'inf_incumplimiento_obs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'inf_incumplimiento_obs',
'table' => 'informe_intersup',
'type' => 3 ),
'placeholder' => array( 'field' => 'inf_incumplimiento_obs',
'table' => null,
'type' => 5 ) ),
'integrated_edit_field12' => array( 'field' => 'cont_cesion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'cont_modifica',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'inf_intersup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'inf_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'inf_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'inf_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'inf_supervisoremail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'supa_documento_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'supa_cargo_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'supa_dependencia_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'supa_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'supa_nombres',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'supa_apellidos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'supb_documento_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'supb_cargo_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'supb_dependencia_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'supb_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'supb_nombres',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'supb_apellidos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'inf_periodicidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'inf_valorcontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'inf_fechasuscripcion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'inf_objeto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'inf_fechacont_i',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'inf_fechacont_f',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'inf_cdp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'inf_rp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'inf_rubrocode',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'inf_rubroname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'inf_plazo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'inf_vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'url_secop',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'inf_usopresupuestal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'mun_ejec',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'inf_anio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'inf_prenum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'cert_modalidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>