<?php
			$optionsArray = array( 'totals' => array( 'interventor_id' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'cont_hash_fk' => array( 'totalsType' => '' ),
'idusrglobal_fk' => array( 'totalsType' => '' ),
'documento_id' => array( 'totalsType' => '' ),
'nombres' => array( 'totalsType' => '' ),
'apellidos' => array( 'totalsType' => '' ),
'cargo_id' => array( 'totalsType' => '' ),
'dependencia_id' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sup_status' => array( 'totalsType' => '' ),
'sup_fechanot' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'fecha_inicio' => array( 'totalsType' => '' ),
'fecha_fin' => array( 'totalsType' => '' ),
'num_sup' => array( 'totalsType' => '' ),
'supa_apellidos' => array( 'totalsType' => '' ),
'supa_cargo_id' => array( 'totalsType' => '' ),
'supa_dependencia_id' => array( 'totalsType' => '' ),
'supa_documento_id' => array( 'totalsType' => '' ),
'supa_email' => array( 'totalsType' => '' ),
'supa_fecha' => array( 'totalsType' => '' ),
'supa_idusrglobal_fk' => array( 'totalsType' => '' ),
'supa_nombres' => array( 'totalsType' => '' ),
'supb_apellidos' => array( 'totalsType' => '' ),
'supb_cargo_id' => array( 'totalsType' => '' ),
'supb_dependencia_id' => array( 'totalsType' => '' ),
'supb_documento_id' => array( 'totalsType' => '' ),
'supb_email' => array( 'totalsType' => '' ),
'supb_fecha' => array( 'totalsType' => '' ),
'supb_idusrglobal_fk' => array( 'totalsType' => '' ),
'supb_nombres' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'idusrglobal_fk',
'sys_date',
'sys_user',
'sup_status',
'sup_fechanot',
'sup_mailnot',
'documento_id',
'nombres',
'apellidos',
'fecha_inicio',
'fecha_fin',
'num_sup',
'supa_apellidos',
'supa_cargo_id',
'supa_dependencia_id',
'supa_documento_id',
'supa_email',
'supa_fecha',
'supa_idusrglobal_fk',
'supa_nombres',
'supb_apellidos',
'supb_cargo_id',
'supb_dependencia_id',
'supb_documento_id',
'supb_email',
'supb_fecha',
'supb_idusrglobal_fk',
'supb_nombres' ),
'exportFields' => array( 'idusrglobal_fk',
'sys_date',
'sys_user',
'sup_status',
'sup_fechanot',
'sup_mailnot',
'documento_id',
'nombres',
'apellidos',
'fecha_inicio',
'fecha_fin',
'num_sup',
'supa_apellidos',
'supa_cargo_id',
'supa_dependencia_id',
'supa_documento_id',
'supa_email',
'supa_fecha',
'supa_idusrglobal_fk',
'supa_nombres',
'supb_apellidos',
'supb_cargo_id',
'supb_dependencia_id',
'supb_documento_id',
'supb_email',
'supb_fecha',
'supb_idusrglobal_fk',
'supb_nombres' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'idusrglobal_fk' => array( 'export_field3' ),
'sys_date' => array( 'export_field4' ),
'sys_user' => array( 'export_field6' ),
'sup_status' => array( 'export_field7' ),
'sup_fechanot' => array( 'export_field8' ),
'sup_mailnot' => array( 'export_field10' ),
'documento_id' => array( 'export_field13' ),
'nombres' => array( 'export_field14' ),
'apellidos' => array( 'export_field15' ),
'fecha_inicio' => array( 'export_field' ),
'fecha_fin' => array( 'export_field1' ),
'num_sup' => array( 'export_field2' ),
'supa_apellidos' => array( 'export_field5' ),
'supa_cargo_id' => array( 'export_field9' ),
'supa_dependencia_id' => array( 'export_field11' ),
'supa_documento_id' => array( 'export_field12' ),
'supa_email' => array( 'export_field16' ),
'supa_fecha' => array( 'export_field17' ),
'supa_idusrglobal_fk' => array( 'export_field18' ),
'supa_nombres' => array( 'export_field19' ),
'supb_apellidos' => array( 'export_field20' ),
'supb_cargo_id' => array( 'export_field21' ),
'supb_dependencia_id' => array( 'export_field22' ),
'supb_documento_id' => array( 'export_field23' ),
'supb_email' => array( 'export_field24' ),
'supb_fecha' => array( 'export_field25' ),
'supb_idusrglobal_fk' => array( 'export_field26' ),
'supb_nombres' => array( 'export_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field3',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field',
'export_field1',
'export_field2',
'export_field5',
'export_field9',
'export_field11',
'export_field12',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field10' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field5' => 'grid',
'export_field9' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field3',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field',
'export_field1',
'export_field2',
'export_field5',
'export_field9',
'export_field11',
'export_field12',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field3',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field',
'export_field1',
'export_field2',
'export_field5',
'export_field9',
'export_field11',
'export_field12',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field3' => array( 'field' => 'idusrglobal_fk',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'sys_date',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'sup_status',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'sup_fechanot',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'sup_mailnot',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'documento_id',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'nombres',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'apellidos',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'fecha_inicio',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'fecha_fin',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'num_sup',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'supa_apellidos',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'supa_cargo_id',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'supa_dependencia_id',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'supa_documento_id',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'supa_email',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'supa_fecha',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'supa_idusrglobal_fk',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'supa_nombres',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'supb_apellidos',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'supb_cargo_id',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'supb_dependencia_id',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'supb_documento_id',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'supb_email',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'supb_fecha',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'supb_idusrglobal_fk',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'supb_nombres',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>