<?php
			$optionsArray = array( 'master' => array( 'contrato' => array( 'preview' => false ),
'contrato_audit' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'id_cont_fk',
'idusrglobal_fk',
'sys_date',
'sys_user',
'sup_status',
'sup_fechanot',
'sup_mailnot',
'documento_id',
'nombres',
'apellidos',
'cargo_id',
'dependencia_id',
'cont_hash_fk',
'fecha_inicio',
'num_sup',
'supa_apellidos',
'supa_cargo_id',
'supa_dependencia_id',
'supa_documento_id',
'supa_email',
'supa_fecha',
'supa_idusrglobal_fk',
'supa_nombres',
'supb_apellidos',
'supb_cargo_id',
'supb_dependencia_id',
'supb_documento_id',
'supb_email',
'supb_fecha',
'supb_idusrglobal_fk',
'supb_nombres' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont_fk' => array( 'integrated_edit_field' ),
'idusrglobal_fk' => array( 'integrated_edit_field2' ),
'sys_date' => array( 'integrated_edit_field3' ),
'sys_user' => array( 'integrated_edit_field5' ),
'sup_status' => array( 'integrated_edit_field6' ),
'sup_fechanot' => array( 'integrated_edit_field7' ),
'sup_mailnot' => array( 'integrated_edit_field9' ),
'documento_id' => array( 'integrated_edit_field12' ),
'nombres' => array( 'integrated_edit_field13' ),
'apellidos' => array( 'integrated_edit_field14' ),
'cargo_id' => array( 'integrated_edit_field15' ),
'dependencia_id' => array( 'integrated_edit_field16' ),
'cont_hash_fk' => array( 'integrated_edit_field1' ),
'fecha_inicio' => array( 'integrated_edit_field4' ),
'num_sup' => array( 'integrated_edit_field8',
'edit_field_label',
'edit_field_tooltip' ),
'supa_apellidos' => array( 'integrated_edit_field10' ),
'supa_cargo_id' => array( 'integrated_edit_field11' ),
'supa_dependencia_id' => array( 'integrated_edit_field17' ),
'supa_documento_id' => array( 'integrated_edit_field18' ),
'supa_email' => array( 'integrated_edit_field19' ),
'supa_fecha' => array( 'integrated_edit_field20' ),
'supa_idusrglobal_fk' => array( 'integrated_edit_field21' ),
'supa_nombres' => array( 'integrated_edit_field22' ),
'supb_apellidos' => array( 'integrated_edit_field23' ),
'supb_cargo_id' => array( 'integrated_edit_field24' ),
'supb_dependencia_id' => array( 'integrated_edit_field25' ),
'supb_documento_id' => array( 'integrated_edit_field26' ),
'supb_email' => array( 'integrated_edit_field27' ),
'supb_fecha' => array( 'integrated_edit_field28' ),
'supb_idusrglobal_fk' => array( 'integrated_edit_field29' ),
'supb_nombres' => array( 'integrated_edit_field30' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'tabs' ),
'section' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field8',
'integrated_edit_field' ),
'section1' => array( 'integrated_edit_field2',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field4' ),
'section2' => array( 'integrated_edit_field21',
'integrated_edit_field18',
'integrated_edit_field11',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field22',
'integrated_edit_field10',
'integrated_edit_field20' ),
'section3' => array( 'integrated_edit_field29',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field30',
'integrated_edit_field23' ),
'section4' => array( 'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'tabs' => 'grid',
'edit_field_label' => 'section',
'edit_field_tooltip' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field2' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field15' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field9' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field21' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field17' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field22' => 'section2',
'integrated_edit_field10' => 'section2',
'integrated_edit_field20' => 'section2',
'integrated_edit_field29' => 'section3',
'integrated_edit_field26' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field25' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field30' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field3' => 'section4',
'integrated_edit_field5' => 'section4',
'integrated_edit_field7' => 'section4',
'integrated_edit_field1' => 'section4' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c1' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field21' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field22' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field10' => array( 'location' => 'section2',
'cellId' => 'c7' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c8' ),
'integrated_edit_field29' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c5' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c6' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c8' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c9' ),
'integrated_edit_field3' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section4',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field1',
'integrated_edit_field4',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30' ),
'edit_field' => array( 'integrated_edit_field8' ),
'tabs' => array( 'tabs' ),
'edit_field_label' => array( 'edit_field_label' ),
'edit_field_tooltip' => array( 'edit_field_tooltip' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'tabs' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field8' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field' => array( 'field' => 'id_cont_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'idusrglobal_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'placeholder' => array( 'field' => 'idusrglobal_fk',
'table' => null,
'type' => 5 ),
'tooltip' => array( 'field' => 'idusrglobal_fk',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field3' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'sup_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'sup_fechanot',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'sup_mailnot',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'documento_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'nombres',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'apellidos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'cargo_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'dependencia_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'cont_hash_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'fecha_inicio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'num_sup',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field10' => array( 'field' => 'supa_apellidos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'supa_cargo_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'supa_dependencia_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'supa_documento_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'supa_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'supa_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'supa_idusrglobal_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'supa_nombres',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'supb_apellidos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'supb_cargo_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'supb_dependencia_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'supb_documento_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'supb_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'supb_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'supb_idusrglobal_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'supb_nombres',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Asignación de supervisión',
'type' => 0 ),
array( 'text' => 'Supervisor 1 | Apoyo',
'type' => 0 ),
array( 'text' => 'Supervisor 2',
'type' => 0 ),
array( 'text' => 'Supervisor 3',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2',
'section3',
'section4' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'num_sup',
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'num_sup',
'separated' => true,
'tooltip' => array( 'field' => 'num_sup',
'table' => null,
'type' => 4 ) ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>