<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cont_ano',
'cont_estado',
'cont_fecha_inicio',
'cont_fechafinal',
'contractor_doc_id',
'contractor_email',
'contractor_nombresfull',
'dpd_dsdpn_b',
'id_cont',
'informes_faltantes',
'informes_sugeridos',
'meses_exactos',
'meses_transcurridos',
'NCONTRATO',
'periodo_meses',
'periodo_name',
'qty_informes_firmados' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_ano' => array( 'import_field' ),
'cont_estado' => array( 'import_field1' ),
'cont_fecha_inicio' => array( 'import_field2' ),
'cont_fechafinal' => array( 'import_field3' ),
'contractor_doc_id' => array( 'import_field4' ),
'contractor_email' => array( 'import_field5' ),
'contractor_nombresfull' => array( 'import_field6' ),
'dpd_dsdpn_b' => array( 'import_field7' ),
'id_cont' => array( 'import_field8' ),
'informes_faltantes' => array( 'import_field9' ),
'informes_sugeridos' => array( 'import_field10' ),
'meses_exactos' => array( 'import_field11' ),
'meses_transcurridos' => array( 'import_field12' ),
'NCONTRATO' => array( 'import_field13' ),
'periodo_meses' => array( 'import_field14' ),
'periodo_name' => array( 'import_field15' ),
'qty_informes_firmados' => array( 'import_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'cont_ano',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cont_estado',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cont_fecha_inicio',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cont_fechafinal',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'contractor_doc_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'contractor_email',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'contractor_nombresfull',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'dpd_dsdpn_b',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'id_cont',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'informes_faltantes',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'informes_sugeridos',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'meses_exactos',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'meses_transcurridos',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'NCONTRATO',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'periodo_meses',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'periodo_name',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'qty_informes_firmados',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>