<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'NCONTRATO' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'contractor_doc_id' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'dpd_dsdpn_b' => array( 'totalsType' => '' ),
'nomcar' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_fecha_acta_liquidacion' => array( 'totalsType' => '' ),
'dias_transcurridos_fechafinal' => array( 'totalsType' => '' ),
'dias_transcurridos_acta_liquidacion' => array( 'totalsType' => '' ),
'tiempo_transcurrido_fechafinal' => array( 'totalsType' => '' ),
'tiempo_transcurrido_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cont_acta_liquidacion',
'cont_ano',
'cont_estado',
'cont_fecha_acta_liquidacion',
'cont_fecha_inicio',
'cont_fechafinal',
'contractor_doc_id',
'contractor_email',
'contractor_email_mincit',
'contractor_nombresfull',
'dias_transcurridos_acta_liquidacion',
'dias_transcurridos_fechafinal',
'dpd_dsdpn_b',
'id_cont',
'NCONTRATO',
'nomcar',
'tiempo_transcurrido_acta_liquidacion',
'tiempo_transcurrido_fechafinal',
'Username',
'usr_email',
'usr_lname',
'usr_name',
'usr_personalid' ),
'exportFields' => array( 'cont_acta_liquidacion',
'cont_ano',
'cont_estado',
'cont_fecha_acta_liquidacion',
'cont_fecha_inicio',
'cont_fechafinal',
'contractor_doc_id',
'contractor_email',
'contractor_email_mincit',
'contractor_nombresfull',
'dias_transcurridos_acta_liquidacion',
'dias_transcurridos_fechafinal',
'dpd_dsdpn_b',
'id_cont',
'NCONTRATO',
'nomcar',
'tiempo_transcurrido_acta_liquidacion',
'tiempo_transcurrido_fechafinal',
'Username',
'usr_email',
'usr_lname',
'usr_name',
'usr_personalid' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_acta_liquidacion' => array( 'export_field' ),
'cont_ano' => array( 'export_field1' ),
'cont_estado' => array( 'export_field2' ),
'cont_fecha_acta_liquidacion' => array( 'export_field3' ),
'cont_fecha_inicio' => array( 'export_field4' ),
'cont_fechafinal' => array( 'export_field5' ),
'contractor_doc_id' => array( 'export_field6' ),
'contractor_email' => array( 'export_field7' ),
'contractor_email_mincit' => array( 'export_field8' ),
'contractor_nombresfull' => array( 'export_field9' ),
'dias_transcurridos_acta_liquidacion' => array( 'export_field10' ),
'dias_transcurridos_fechafinal' => array( 'export_field11' ),
'dpd_dsdpn_b' => array( 'export_field12' ),
'id_cont' => array( 'export_field13' ),
'NCONTRATO' => array( 'export_field14' ),
'nomcar' => array( 'export_field15' ),
'tiempo_transcurrido_acta_liquidacion' => array( 'export_field16' ),
'tiempo_transcurrido_fechafinal' => array( 'export_field17' ),
'Username' => array( 'export_field18' ),
'usr_email' => array( 'export_field19' ),
'usr_lname' => array( 'export_field20' ),
'usr_name' => array( 'export_field21' ),
'usr_personalid' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'cont_acta_liquidacion',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'cont_ano',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'cont_estado',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'cont_fecha_acta_liquidacion',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cont_fecha_inicio',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cont_fechafinal',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'contractor_doc_id',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'contractor_email',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'contractor_email_mincit',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'contractor_nombresfull',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'dias_transcurridos_acta_liquidacion',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'dias_transcurridos_fechafinal',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'dpd_dsdpn_b',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'id_cont',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'NCONTRATO',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'nomcar',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'tiempo_transcurrido_acta_liquidacion',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'tiempo_transcurrido_fechafinal',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Username',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'usr_email',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'usr_lname',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'usr_name',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'usr_personalid',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>