<?php
$dalTableinterventor_interno = array();
$dalTableinterventor_interno["interventor_id"] = array("type"=>3,"varname"=>"interventor_id", "name" => "interventor_id", "autoInc" => "1");
$dalTableinterventor_interno["num_sup"] = array("type"=>16,"varname"=>"num_sup", "name" => "num_sup", "autoInc" => "0");
$dalTableinterventor_interno["id_cont_fk"] = array("type"=>3,"varname"=>"id_cont_fk", "name" => "id_cont_fk", "autoInc" => "0");
$dalTableinterventor_interno["cont_hash_fk"] = array("type"=>200,"varname"=>"cont_hash_fk", "name" => "cont_hash_fk", "autoInc" => "0");
$dalTableinterventor_interno["idusrglobal_fk"] = array("type"=>3,"varname"=>"idusrglobal_fk", "name" => "idusrglobal_fk", "autoInc" => "0");
$dalTableinterventor_interno["documento_id"] = array("type"=>3,"varname"=>"documento_id", "name" => "documento_id", "autoInc" => "0");
$dalTableinterventor_interno["nombres"] = array("type"=>200,"varname"=>"nombres", "name" => "nombres", "autoInc" => "0");
$dalTableinterventor_interno["apellidos"] = array("type"=>200,"varname"=>"apellidos", "name" => "apellidos", "autoInc" => "0");
$dalTableinterventor_interno["cargo_id"] = array("type"=>3,"varname"=>"cargo_id", "name" => "cargo_id", "autoInc" => "0");
$dalTableinterventor_interno["dependencia_id"] = array("type"=>3,"varname"=>"dependencia_id", "name" => "dependencia_id", "autoInc" => "0");
$dalTableinterventor_interno["sys_date"] = array("type"=>7,"varname"=>"sys_date", "name" => "sys_date", "autoInc" => "0");
$dalTableinterventor_interno["sys_time"] = array("type"=>135,"varname"=>"sys_time", "name" => "sys_time", "autoInc" => "0");
$dalTableinterventor_interno["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user", "autoInc" => "0");
$dalTableinterventor_interno["sup_status"] = array("type"=>16,"varname"=>"sup_status", "name" => "sup_status", "autoInc" => "0");
$dalTableinterventor_interno["sup_fechanot"] = array("type"=>135,"varname"=>"sup_fechanot", "name" => "sup_fechanot", "autoInc" => "0");
$dalTableinterventor_interno["sup_horanot"] = array("type"=>134,"varname"=>"sup_horanot", "name" => "sup_horanot", "autoInc" => "0");
$dalTableinterventor_interno["sup_mailnot"] = array("type"=>200,"varname"=>"sup_mailnot", "name" => "sup_mailnot", "autoInc" => "0");
$dalTableinterventor_interno["sup_fechanot2"] = array("type"=>7,"varname"=>"sup_fechanot2", "name" => "sup_fechanot2", "autoInc" => "0");
$dalTableinterventor_interno["sup_mailnot2"] = array("type"=>200,"varname"=>"sup_mailnot2", "name" => "sup_mailnot2", "autoInc" => "0");
$dalTableinterventor_interno["fecha_inicio"] = array("type"=>7,"varname"=>"fecha_inicio", "name" => "fecha_inicio", "autoInc" => "0");
$dalTableinterventor_interno["fecha_fin"] = array("type"=>7,"varname"=>"fecha_fin", "name" => "fecha_fin", "autoInc" => "0");
$dalTableinterventor_interno["supa_idusrglobal_fk"] = array("type"=>3,"varname"=>"supa_idusrglobal_fk", "name" => "supa_idusrglobal_fk", "autoInc" => "0");
$dalTableinterventor_interno["supa_documento_id"] = array("type"=>3,"varname"=>"supa_documento_id", "name" => "supa_documento_id", "autoInc" => "0");
$dalTableinterventor_interno["supa_nombres"] = array("type"=>200,"varname"=>"supa_nombres", "name" => "supa_nombres", "autoInc" => "0");
$dalTableinterventor_interno["supa_apellidos"] = array("type"=>200,"varname"=>"supa_apellidos", "name" => "supa_apellidos", "autoInc" => "0");
$dalTableinterventor_interno["supa_cargo_id"] = array("type"=>3,"varname"=>"supa_cargo_id", "name" => "supa_cargo_id", "autoInc" => "0");
$dalTableinterventor_interno["supa_dependencia_id"] = array("type"=>3,"varname"=>"supa_dependencia_id", "name" => "supa_dependencia_id", "autoInc" => "0");
$dalTableinterventor_interno["supa_email"] = array("type"=>200,"varname"=>"supa_email", "name" => "supa_email", "autoInc" => "0");
$dalTableinterventor_interno["supa_fecha"] = array("type"=>135,"varname"=>"supa_fecha", "name" => "supa_fecha", "autoInc" => "0");
$dalTableinterventor_interno["supb_idusrglobal_fk"] = array("type"=>3,"varname"=>"supb_idusrglobal_fk", "name" => "supb_idusrglobal_fk", "autoInc" => "0");
$dalTableinterventor_interno["supb_documento_id"] = array("type"=>3,"varname"=>"supb_documento_id", "name" => "supb_documento_id", "autoInc" => "0");
$dalTableinterventor_interno["supb_nombres"] = array("type"=>200,"varname"=>"supb_nombres", "name" => "supb_nombres", "autoInc" => "0");
$dalTableinterventor_interno["supb_apellidos"] = array("type"=>200,"varname"=>"supb_apellidos", "name" => "supb_apellidos", "autoInc" => "0");
$dalTableinterventor_interno["supb_cargo_id"] = array("type"=>3,"varname"=>"supb_cargo_id", "name" => "supb_cargo_id", "autoInc" => "0");
$dalTableinterventor_interno["supb_dependencia_id"] = array("type"=>3,"varname"=>"supb_dependencia_id", "name" => "supb_dependencia_id", "autoInc" => "0");
$dalTableinterventor_interno["supb_email"] = array("type"=>200,"varname"=>"supb_email", "name" => "supb_email", "autoInc" => "0");
$dalTableinterventor_interno["supb_fecha"] = array("type"=>135,"varname"=>"supb_fecha", "name" => "supb_fecha", "autoInc" => "0");
$dalTableinterventor_interno["interventor_id"]["key"]=true;

$dal_info["dbct_at_localhost__interventor_interno"] = &$dalTableinterventor_interno;
?>