<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_interventor_interno  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterAdd"]=true;


		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
$email = $values['sup_mailnot'];
$from = $_SESSION['correosmtp'];
$msg = "
<!DOCTYPE html>
<html lang='es'>
<head>
  <meta charset='UTF-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <title>Notificación de Designación como Supervisor de Contratos</title>
  <style>
    /* Estilos para el cuerpo del correo */
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 0;
      padding: 0;
    }
    /* Estilos para el encabezado con el logo */
    .header {
      background-color: #f8f9fa;
      padding: 20px;
      text-align: center;
    }
    .header img {
      max-width: 200px;
    }
    /* Estilos para el contenido del correo */
    .content {
      padding: 20px;
    }
  </style>
</head>
<body>
  <!-- Encabezado con el logo -->
  <div class='header'>
    <img src='".$_SESSION['logo']."' alt='".$_SESSION['GEntidad']."'>
  </div>

  <!-- Contenido del correo -->
  <div class='content'>
    <h2>Notificación de Designación como Supervisor de Contratos</h2>
    <p>Estimada/o ".$values['nombres'].",</p>
    <p>Nos complace informarle que ha sido designado como Supervisor de Contratos a partir de la fecha ".$values['fecha_inicio'].". Su papel será crucial en garantizar el cumplimiento y la eficacia de nuestros acuerdos contractuales.</p>
    <p>Como supervisor de contratos, sus responsabilidades incluirán:</p>
    <ul>
      <li>Programación de pagos.</li>
      <li>Programación de entrega de informes.</li>
      <li>Revisión y firma de informes de supervisión.</li>
      <li>Elaboración de CRS (Certificados de Recibido a Satisfacción).</li>
      <li>Seguimiento a las obligaciones del contrato.</li>
      <li>En caso de existir, elaborar el acta de liquidación en las fechas programadas.</li>
      <li>Verificación de publicación en SECOP II.</li>
    </ul>
    <p>Por favor, póngase en contacto con el Grupo de Contratos de la Secretaría General, para coordinar cualquier acción adicional que sea necesaria en el marco de sus responsabilidades.</p>
    <p>Confiamos en sus habilidades y experiencia para desempeñar este papel de manera efectiva y contribuir al éxito de nuestros proyectos. Para ver el detalle de esta asignacion visite : <a href='".$_SESSION['GURL']."'>".$_SESSION['GURL']."</a></br></p>
    <p>Saludos cordiales,</p></br>
    <p>Grupo de Contratos<br>
    Secretaría General<br>
    Ministerio de Comercio, Industria y Turismo</p>
  </div>
</body>
</html>
";

$subject = "Notificación de Designación como Supervisor de Contratos";

$ret = runner_mail(array(
    'to' => $email,
    'bcc' => $_SESSION['EmailBCC'],
    'subject' => $subject,
    'htmlbody' => $msg,
    'from' => $from
));

if (!$ret["mailed"]) {
    echo $ret["message"];
}





// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		if($values['sup_status'] == 2){
$email = $values['sup_mailnot'];
$from = $_SESSION['correosmtp'];
$msg = "
<!DOCTYPE html>
<html lang='es'>
<head>
  <meta charset='UTF-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <title>Notificación de Revocación como Supervisor de Contratos</title>
  <style>
    /* Estilos para el cuerpo del correo */
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 0;
      padding: 0;
    }
    /* Estilos para el encabezado con el logo */
    .header {
      background-color: #f8f9fa;
      padding: 20px;
      text-align: center;
    }
    .header img {
      max-width: 200px;
    }
    /* Estilos para el contenido del correo */
    .content {
      padding: 20px;
    }
  </style>
</head>
<body>
  <!-- Encabezado con el logo -->
  <div class='header'>
    <img src='".$_SESSION['logo']."' alt='".$_SESSION['GEntidad']."'>
  </div>

  <!-- Contenido del correo -->
  <div class='content'>
    <h2>Notificación de Revocación como Supervisor de Contratos</h2>
    <p>Estimada/o ".$values['nombres'].",</p>
    <p>Queremos informarle que su designación como Supervisor de Contratos ha sido revocada a partir de la fecha ".$values['fecha_fin'].".</p>
    <p>Apreciamos su contribución y esfuerzos durante su tiempo como supervisor de contratos. A partir de ahora, le pedimos que se comunique con el Grupo de Contratos de la Secretaría General para coordinar cualquier acción adicional que sea necesaria en el marco de sus responsabilidades anteriores.</p>
    <p>Si tiene alguna pregunta o necesita más información, no dude en ponerse en contacto con nosotros.</p>
    <p>Saludos cordiales,</p>
    <p>Grupo de Contratos<br>
    Secretaría General<br>
    Ministerio de Comercio, Industria y Turismo</p>
  </div>
</body>
</html>
";

$subject = "Notificación de Revocación como Supervisor de Contratos";

$ret = runner_mail(array(
    'to' => $email,
    'bcc' => $_SESSION['EmailBCC'],
    'subject' => $subject,
    'htmlbody' => $msg,
    'from' => $from
));

if (!$ret["mailed"]) {
    echo $ret["message"];
}


}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
